<?php

/**
 * This file is part of the dsExtDirectPlugin
 *
 * @package   dsExtDirectPlugin
 * @author    Daniel Stevens <danhstevens@gmail.com>
 * @copyright Copyright (c) 2009, Daniel Stevens
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 * @version   SVN: $Id$
 */

/**
 * dsExtDirectGenerateApiTask generates the API Spec JS for Ext.Direct
 *
 * @package    dsExtDirectPlugin
 * @author     Daniel Stevens <danhstevens@gmail.com>
 */

class dsExtDirectGenerateApiTask extends sfGeneratorBaseTask
{

  /**
   * The default environment
   *
   * @var string
   */
  const DEFAULT_ENVIRONMENT = 'extdirect';
  
  /**
   * @see sfTask
   */
  protected function configure()
  {
    $this->namespace        = 'extdirect';
    $this->name             = 'generate-api';
    $this->briefDescription = 'Generates an Ext.Direct js spec file from your marked module actions';
    $this->detailedDescription = <<<EOF
The [extdirect:generate-api|INFO] task generates an Ext.Direct js spec file and from your marked module actions to expose them as a Ext.Direct api method.
Call it with:

  [./symfony extdirect:generate-api yourapp|INFO]

The js file will be created in the [web/js|COMMENT] directory:

  [web/js/extdirect_api.js|INFO]
  
And a yml file will be created in the [apps/yourapp/config|COMMENT] directory:

  [apps/yourapp/config/extdirect_api.yml|INFO]

This task also creates a front controller script in the [web/|COMMENT] directory:

  [web/extdirect.php|INFO]

You can change the name of your environment, front controller, js & yml files by using the [environment|COMMENT] option:

  [./symfony extdirect:generate-api yourapp --environment extdirect|INFO]

  or

  [./symfony extdirect:generate-api yourapp -e extdirect|INFO]

You can enable debugging for the controller by using the [enabledebug|COMMENT] option:

  [./symfony extdirect:generate-api yourapp --enabledebug|INFO]

  or

  [./symfony extdirect:generate-api yourapp -d|INFO]

EOF;

    $this->addArgument('application', sfCommandArgument::REQUIRED, 'The application name');

    $this->addOption('environment', 'e', sfCommandOption::PARAMETER_REQUIRED, 'The environment to use for webservice mode', self::DEFAULT_ENVIRONMENT);
    $this->addOption('enabledebug', 'd', sfCommandOption::PARAMETER_NONE, 'Enables debugging in generated controller');
  }
  
  protected function execute($arguments = array(), $options = array())
  {
    $app  = $arguments['application'];
    $env  = $options['environment'];
    $dbg  = $options['enabledebug'];
    $file = $env;
    
    $this->buildControllerFile($file, $app, $env, $dbg);
    
    $api = array();
    foreach($this->getModules() as $module)
    {
      if($this->loadModuleClassFile($module))
      { 
        $class = new ReflectionClass($module.'Actions');
        foreach($class->getMethods(ReflectionMethod::IS_PUBLIC) as $method)
        {
          $comments = $method->getDocComment();
          
          if(strpos($comments, '@extdirect-enable') !== false)
          {
            preg_match('/@extdirect-len (?P<len>\\d*)/', $comments, $method_len);
            $method_len = isset($method_len['len']) && !empty($method_len['len']) ? $method_len['len'] : 0;
            $method_name = $this->getShortMethodName($method->getName());
            $method_fh = strpos($comments, '@extdirect-formhandler') !== false ? true : false;
            $method_def = array('len' => $method_len, 'formHandler' => $method_fh);
            
            if(!isset($api[$module]))
            {
              $api[$module] = array('methods' => array($method_name => $method_def));
            }
            else 
            {
              $api[$module]['methods'][$method_name] = $method_def;
            }
          }
        }
      }
    }
    
    $this->buildApiYaml($file, $api);
    $this->buildApiJs($file, $api);
  }
  
  protected function buildControllerFile($controller, $application, $environment, $debug)
  {
    $template = sfConfig::get('sf_symfony_lib_dir').'/task/generator/skeleton/app/web/index.php';
    $pathname = sprintf('%s/%s.php', sfConfig::get('sf_web_dir'), $controller);

    if(file_exists($pathname))
    {
      $this->getFilesystem()->remove($pathname);
    }
    $this->getFilesystem()->copy($template, $pathname);
    $this->getFilesystem()->replaceTokens($pathname, '##', '##', array(
      'IP_CHECK'    => '',
      'APP_NAME'    => $application,
      'ENVIRONMENT' => $environment,
      'IS_DEBUG'    => $debug ? 'true' : 'false',
    ));
  }
  
  protected function buildApiYaml($file, $api)
  {
    $head = "# DO NOT MODIFY\n# Generated by extdirect:generate-api task\n";
    $path = sfConfig::get('sf_app_config_dir').'/'.$file.'_api.yml';
    file_put_contents($path, $head.sfYaml::dump($api));
    $this->logSection('extdirect', 'Generated YAML API Spec: '.$path);
  }
  
  protected function buildApiJs($file, $api)
  {
    $actions = array();
    
    foreach($api as $actionName => $action)
    {
      $methods = array();
      
      foreach ($action['methods'] as $methodName => $method)
      {
        $methodDef = array(
          'name' => $methodName,
          'len' => isset($method['len']) ? $method['len'] : 0
        );
        
        if(isset($method['formHandler']) && $method['formHandler'])
        {
          $methodDef['formHandler'] = true;
        }
        
        $methods[] = $methodDef;
      }
      $actions[$actionName] = $methods;
    }
    
    $config = array(
      'url' => sfConfig::get('app_ds_ext_direct_plugin_router_url', "/$file.php/dsExtDirect/router"),
      'type' => sfConfig::get('app_ds_ext_direct_plugin_provider_type', 'remoting'),
      'actions' => $actions
    );
    
    $js = sfConfig::get('app_ds_ext_direct_plugin_js_var', 'Ext.app.'.strtoupper($file).'_API') . ' = ' . json_encode($config) . ';';
    
    $path = sfConfig::get('sf_web_dir').'/js/'.$file.'_api.js';
    file_put_contents($path, $js);
    $this->logSection('extdirect', 'Generated JS API Spec: '.$path);
  }
  
  protected function getModules()
  {
    return sfFinder::type('directory')->name('*')->relative()->maxdepth(0)->in(sfConfig::get('sf_app_module_dir'));
  }
  
  protected function loadModuleClassFile($module)
  {
    $module_classfile = sfConfig::get('sf_app_module_dir').'/'.$module.'/actions/actions.class.php';

    return file_exists($module_classfile) && !preg_match('/class(.*)Actions(.*)extends(.*)auto/', file_get_contents($module_classfile)) ? require_once($module_classfile) : false;
  }
  
  protected function loadModuleConfigFile($module)
  {
    $module_configfile = $this->getModuleConfigFilePath($module);

    return file_exists($module_configfile) ? sfYaml::load($module_configfile) : array();
  }
  
  protected function getModuleConfigFilePath($module)
  {
    return sfConfig::get('sf_app_module_dir').'/'.$module.'/config/module.yml';
  }
  
  protected function getShortMethodName($method_name)
  {
    if(strpos($method_name, 'execute') === 0)
    {
      $method_name = substr($method_name, 7);
    }
    
    return strtolower($method_name{0}).substr($method_name, 1);
  }
}

?>